# Generated by Django 3.0.5 on 2022-07-15 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20201209_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_pic',
            field=models.ImageField(blank=True, null=True, upload_to='question/'),
        ),
    ]
