# Generated by Django 3.0.5 on 2022-07-15 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_question_question_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic/Teacher/'),
        ),
    ]
