# Generated by Django 3.0.5 on 2022-07-15 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_auto_20220715_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='option1_pic',
            field=models.ImageField(blank=True, null=True, upload_to='question/'),
        ),
        migrations.AddField(
            model_name='question',
            name='option2_pic',
            field=models.ImageField(blank=True, null=True, upload_to='question/'),
        ),
        migrations.AddField(
            model_name='question',
            name='option3_pic',
            field=models.ImageField(blank=True, null=True, upload_to='question/'),
        ),
        migrations.AddField(
            model_name='question',
            name='option4_pic',
            field=models.ImageField(blank=True, null=True, upload_to='question/'),
        ),
    ]
